### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sru**

### CODE REVIEW

**Comment by sru** [comment]
Is it still going?

**Comment by Kentoseth** [comment]
The ideas part? Yes it is. I think your commit may have slipped through somehow (my apologies).

**Comment by sru** [comment]
The commit is still not merged. Also, when are we going to start building some of these?

**Comment by Kentoseth** [comment]
Hi there

> Also, when are we going to start building some of these?

As soon as I have the system setup. We should be starting in around 10 days or so. It will take a bit of time to get everyone onto the platform, so time-wise, that is one of the factors.

**Comment by sru** [comment]
What platform are you using?

**Comment by Kentoseth** [comment]
@sru : 

I provided that info via email.

However, the name is: Phabricator

**Comment by Kentoseth** [comment]
Added.

**Pull request closed without merging**
